// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJcX8lwkvKpyf5JI6BWE-yqMR7OIz7Bnk',
    appId: '1:409104629491:web:441b9b076309023c018186',
    messagingSenderId: '409104629491',
    projectId: 'labtrack-208b3',
    authDomain: 'labtrack-208b3.firebaseapp.com',
    storageBucket: 'labtrack-208b3.firebasestorage.app',
    measurementId: 'G-65Y4V3RCC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy_LrMgoV4vY2gNwQuCFxrVCiVpRfjOjk',
    appId: '1:409104629491:android:6a033c53d3068fdb018186',
    messagingSenderId: '409104629491',
    projectId: 'labtrack-208b3',
    storageBucket: 'labtrack-208b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDCLiz6tt_PfKGo6qF-4HEm_6ZoL1JJMI',
    appId: '1:409104629491:ios:0b0474ebab3bb673018186',
    messagingSenderId: '409104629491',
    projectId: 'labtrack-208b3',
    storageBucket: 'labtrack-208b3.firebasestorage.app',
    iosClientId: '409104629491-dljut29rg36hjhi8qlskjimnemue3hgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.labtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDCLiz6tt_PfKGo6qF-4HEm_6ZoL1JJMI',
    appId: '1:409104629491:ios:0b0474ebab3bb673018186',
    messagingSenderId: '409104629491',
    projectId: 'labtrack-208b3',
    storageBucket: 'labtrack-208b3.firebasestorage.app',
    iosClientId: '409104629491-dljut29rg36hjhi8qlskjimnemue3hgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.labtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJcX8lwkvKpyf5JI6BWE-yqMR7OIz7Bnk',
    appId: '1:409104629491:web:b16fa89ff14e9083018186',
    messagingSenderId: '409104629491',
    projectId: 'labtrack-208b3',
    authDomain: 'labtrack-208b3.firebaseapp.com',
    storageBucket: 'labtrack-208b3.firebasestorage.app',
    measurementId: 'G-82BHBNMWTY',
  );
}
